#Student Management System Configuration
spring:
  application:
    name: student-management

  datasource:
    url: jdbc:postgresql://localhost:5432/student_management_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    database: postgresql
    open-in-view: true

#Server Configuration:
server:
  port: 8081

#Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Springdoc Configuration:
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /student-api.html
    operationsSorter: method
    tagsSorter: alpha
    default-sort: method,asc


app:
  customer:
    location:
      prefix: "/api/customers/"
