#file: noinspection SpringBootApplicationYaml
spring:
  application:
    name: student-management

  datasource:
    url: jdbc:postgresql://localhost:5432/student_management_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    database: postgresql



server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /student-api.html

